# Generated by Django 6.0.2 on 2026-03-13 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': 'Достижение пользователя', 'verbose_name_plural': 'Достижения пользователей'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='🏆', max_length=10, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='is_rare',
            field=models.BooleanField(default=False, verbose_name='Редкое'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название достижения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='points',
            field=models.IntegerField(default=10, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement', verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
