# Generated by Django 6.0.2 on 2026-04-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_comment_author_alter_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes_images/', verbose_name='Картинка'),
        ),
    ]
